Thought: problems are solved, not by telling, but by asking 
- true guidance is to guide the ideas generated by one in the right direction, and not providing a solution to the problem
- true guidance makes sure that the listener is actively interacting with the guidance
